# SwiftLint Configuration for TenThousand
# Aligned with CODE_CONVENTIONS.md

# Rules to enable
opt_in_rules:
  - explicit_type_interface
  - force_unwrapping
  - private_outlet
  - private_action
  - let_var_whitespace
  - mark
  - missing_docs
  - modifier_order
  - multiline_arguments
  - multiline_function_chains
  - multiline_parameters
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - redundant_nil_coalescing
  - sorted_imports
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition

# Disabled rules
disabled_rules:
  - todo # Allow TODO comments for development
  - trailing_whitespace # Let formatter handle this
  - line_length # macOS development often needs longer lines

# Customized rules
identifier_name:
  min_length: 2
  max_length: 60
  excluded:
    - id
    - x
    - y
    - i
    - j

type_name:
  min_length: 3
  max_length: 60

function_body_length:
  warning: 60
  error: 100

file_length:
  warning: 500
  error: 1000

type_body_length:
  warning: 300
  error: 500

# Force unwrapping - critical per conventions
force_unwrap:
  severity: error

# Force cast - avoid unless absolutely necessary
force_cast:
  severity: warning

# Enforce no magic numbers (aligned with no magic literals convention)
number_separator:
  minimum_length: 5

# Cyclomatic complexity
cyclomatic_complexity:
  warning: 10
  error: 20

# Nesting depth
nesting:
  type_level: 2
  statement_level: 5

# Custom rules for conventions
custom_rules:
  no_magic_numbers_in_frames:
    name: "No Magic Numbers in Frames"
    regex: '\.frame\(width:\s*\d+|height:\s*\d+\)'
    message: "Use named constants from DesignSystem or private enum Const for frame dimensions"
    severity: warning

  no_magic_numbers_in_padding:
    name: "No Magic Numbers in Padding"
    regex: '\.padding\(\s*\d+\s*\)'
    message: "Use named constants from Spacing or private enum Const for padding values"
    severity: warning

  no_magic_numbers_in_corner_radius:
    name: "No Magic Numbers in Corner Radius"
    regex: '\.cornerRadius\(\s*\d+\s*\)'
    message: "Use named constants from DesignSystem or private enum Const for corner radius"
    severity: warning

  private_enum_const:
    name: "Prefer private enum Const"
    regex: 'private\s+struct\s+Const\s*\{'
    message: "Prefer 'private enum Const' over 'private struct Const' to prevent instantiation"
    severity: warning

# Excluded files/directories
excluded:
  - .build
  - Carthage
  - Pods
  - DerivedData
  - .swiftpm
  - TenThousand.xcodeproj
  - TenThousandTests/TenThousandTests.swift # Generated test file
  - TenThousandUITests/TenThousandUITests.swift # Generated test file

# Included files
included:
  - TenThousand
  - TenThousandTests
  - TenThousandUITests

# Reporter
reporter: "xcode"

# Strict mode - treat warnings as errors in CI
# strict: true # Uncomment for CI/CD to fail on warnings
